name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Gradle
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v1

      - name: Set execute permissions for gradlew
        run: chmod +x gradlew

      - name: Generate Proto
        run: ./gradlew generateProto

      - name: Build with Gradle Wrapper
        run: ./gradlew build
